app:
    resource: '@AppBundle/Controller/'
    type: annotation

mmc_sonata_admin:
    resource: "@MMCSonataAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /admin
